Repository pagopa/pagopa-reporting-orgs-enrollment, pull requests merged in 2023-08, with the labels that each got.

#6 [PAGOPA-1136] feat: migrated to GitHub Actions
  .github/PULL_REQUEST_TEMPLATE.md
  .github/auto_assign.yml
  .github/release.yml
  .github/workflows/anchore.yml
  .github/workflows/check_pr.yml
  .github/workflows/code_review.yml
  .github/workflows/create_dashboard.yaml
  .github/workflows/deploy_with_github_runner.yml
  .github/workflows/integration_test.yml
  .github/workflows/release_deploy.yml
  .github/workflows/update_code.yml
  .gitignore
  .identity/00_data.tf
  .identity/02_application_action.tf
  .identity/03_github_environment.tf
  .identity/99_main.tf
  .identity/99_variables.tf
  .identity/env/dev/backend.ini
  .identity/env/dev/backend.tfvars
  .identity/env/dev/terraform.tfvars
  .identity/env/prod/backend.ini
  .identity/env/prod/backend.tfvars
  .identity/env/prod/terraform.tfvars
  .identity/env/uat/backend.ini
  .identity/env/uat/backend.tfvars
  .identity/env/uat/terraform.tfvars
  .identity/terraform.sh
Labels: size/large

#4 Performance test
  .devops/performance-test-pipelines.yml
  .gitignore
  helm/values-uat.yaml
  performance-test/README.md
  performance-test/docker-compose.yaml
  performance-test/nginx/nginx.conf
  performance-test/run_performance_test.sh
  performance-test/src/create_organization.js
  performance-test/src/create_organization_quarkus.js
  performance-test/src/delete_organization.js
  performance-test/src/environments/dev.environment.json
  performance-test/src/environments/local.environment.json
  performance-test/src/environments/uat.environment.json
  performance-test/src/full_load_test.js
  performance-test/src/get_organization.js
  performance-test/src/get_organizations.js
  performance-test/src/local.environment.json
  performance-test/src/modules/client.js
  performance-test/src/modules/helpers.js
  performance-test/src/test-types/constant.json
  performance-test/src/test-types/load.json
  performance-test/src/test-types/ramping.json
  performance-test/src/test-types/spike.json
  performance-test/src/test-types/stress.json
Labels: documentation

#7 [PAGOPA-1142] fix: updated integration and smoke tests
  .devops/code-review-pipelines.yml
  .devops/deploy-pipelines.yml
  .github/workflows/code_review.yml
  .github/workflows/create_dashboard.yaml
  .github/workflows/integration_test.yml
  .identity/.terraform.lock.hcl
  .identity/00_data.tf
  .identity/03_github_environment.tf
  .opex/env/prod/backend.ini
  .opex/env/prod/backend.tfvars
  .opex/env/prod/config.yaml
  .opex/env/prod/terraform.tfvars
  docker/README.md
  docker/docker-compose.yml
  docker/run_docker.sh
  integration-test/README.MD
  integration-test/config/properties.json
  integration-test/package.json
  integration-test/run_integration_test.sh
  integration-test/src/README.md
  integration-test/src/config/.env.dev
  integration-test/src/config/.env.local
  integration-test/src/config/.env.uat
  integration-test/src/features/organizations.feature
  integration-test/src/package.json
  integration-test/src/step_definitions/support/common.js
  integration-test/src/step_definitions/support/organizations_steps.js
  integration-test/src/step_definitions/support/reporting_orgs_enrollment_client.js
  integration-test/src/step_definitions/support/steps.js
Labels: documentation, size/large

#8 fix: Update helm values
  .gitignore
  CODEOWNERS
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
Labels: size/small
